import {getBlogs,byNewest,dateDe,readingTime} from './blogs.js';
import {card} from './ui.js';
import {filterPosts} from './search.js';
import {markdown} from './markdown.js';

const $=s=>document.querySelector(s);
document.querySelectorAll('#year').forEach(e=>e.textContent=new Date().getFullYear());
try { const blogs=byNewest(await getBlogs()); location.pathname.endsWith('blog.html') ? renderArticle(blogs) : renderList(blogs); } catch(e) { const target=$('#posts')||$('#article'); target.innerHTML=`<p class="empty">${e.message}</p>`; }
function renderList(blogs) { const posts=$('#posts'),search=$('#search'),category=$('#categoryFilter'),tagBox=$('#tagFilters'); const cats=[...new Set(blogs.map(b=>b.category).filter(Boolean))]; category.insertAdjacentHTML('beforeend',cats.map(c=>`<option>${c}</option>`).join('')); const tags=[...new Set(blogs.flatMap(b=>b.tags||[]))]; tagBox.innerHTML=tags.map(t=>`<button class="tag tag-filter" data-tag="${t}">${t}</button>`).join(''); let active=''; const render=()=>{const result=filterPosts(blogs,{query:search.value,category:category.value,tag:active});posts.innerHTML=result.length?result.map(card).join(''):'<p class="empty">Keine passenden Beiträge gefunden.</p>';$('#postCount').textContent=`${result.length} Beitrag${result.length===1?'':'e'}`};search.addEventListener('input',render);category.addEventListener('change',render);tagBox.addEventListener('click',e=>{if(!e.target.dataset.tag)return;active=active===e.target.dataset.tag?'':e.target.dataset.tag;tagBox.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.tag===active));render()});render(); }
function setSocialMeta(post) { const description=post.socialDescription||post.seoDescription||post.excerpt||''; const data={'description':description,'og:title':post.socialTitle||post.title,'og:description':description,'og:image':post.socialImage||post.image||'','twitter:title':post.socialTitle||post.title,'twitter:description':description,'twitter:image':post.socialImage||post.image||''}; Object.entries(data).forEach(([name,value])=>{const meta=document.querySelector(`meta[property="${name}"],meta[name="${name}"]`);if(meta)meta.content=value;}); }
function renderArticle(blogs) { const params=new URLSearchParams(location.search); const key=params.get('post')||params.get('id')||params.get('slug'); const post=blogs.find(p=>p.id===key||p.slug===key); const article=$('#article'); if(!post){article.innerHTML='<p class="empty">Dieser Beitrag wurde nicht gefunden.</p>';return;} document.title=`${post.title} · Lokro`;setSocialMeta(post);article.innerHTML=`<p class="eyebrow">${post.category||'BLOG'}${post.important?' · WICHTIG':''}</p><h1>${post.title}</h1><div class="article-meta"><span>${dateDe(post.date)}</span><span>·</span><span>${post.author||'Lokro'}</span><span>·</span><span>${readingTime(post.content)} Min. Lesezeit</span></div>${post.image?`<img class="article-hero" src="${post.image}" alt="">`:''}<div class="article-content">${markdown(post.content)}</div><div class="article-tags">${(post.tags||[]).map(t=>`<span class="tag">${t}</span>`).join('')}</div>`; const headings=[...article.querySelectorAll('h2,h3')];if(headings.length){const toc=$('#toc');toc.hidden=false;toc.querySelector('nav').innerHTML=headings.map(h=>`<a href="#${h.id}">${h.textContent}</a>`).join('');}const related=blogs.filter(x=>x.slug!==post.slug&&((x.category&&x.category===post.category)||x.tags?.some(t=>post.tags?.includes(t)))).slice(0,3);$('#related').innerHTML=(related.length?related:blogs.filter(x=>x.slug!==post.slug).slice(0,3)).map(card).join(''); }
