import {getBlogs,saveLocal,clearLocal,slugify,readingTime,byNewest} from '../js/blogs.js';import {markdown,excerpt as createExcerpt} from '../js/markdown.js';
const $=id=>document.getElementById(id);const fields=['id','title','slug','date','author','category','tags','excerpt','image','seoDescription','important','content'];let posts=[];let current=null;let slugTouched=false;
const today=()=>new Date().toISOString().slice(0,10);function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function dataFromForm(){const post={};fields.forEach(f=>post[f]=f==='important'?$(f).checked:$(f).value.trim());post.tags=post.tags?post.tags.split(',').map(x=>x.trim()).filter(Boolean):[];post.id=post.id||post.slug;post.excerpt=post.excerpt||createExcerpt(post.content);return post}
function renderList(){const box=$('postList');box.innerHTML=byNewest(posts).map(p=>`<button class="post-item ${p.id===current?'active':''}" data-id="${p.id}"><b>${p.title}</b><small>${p.date} · ${p.category||'Ohne Kategorie'}</small></button>`).join('')||'<p class="muted">Noch keine Beiträge.</p>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>load(b.dataset.id))}
function preview(){const p=dataFromForm();$('readingTime').textContent=`${readingTime(p.content)} Min.`;$('previewContent').innerHTML=`<p class="eyebrow">${p.category||'BLOG'}${p.important?' · WICHTIG':''}</p><h1>${p.title||'Dein Beitragstitel'}</h1><p class="muted">${p.date||today()} · ${p.author||'Lokro'}</p>${p.image?`<img src="${p.image}" alt="">`:''}${markdown(p.content||'Hier erscheint deine Live-Vorschau.')}`;$('openPreview').href=`../blog.html?slug=${encodeURIComponent(p.slug||'vorschau')}`}
function load(id){const p=posts.find(x=>x.id===id);if(!p)return;current=id;fields.forEach(f=>$(f)[f==='important'?'checked':'value']=f==='tags'?(p.tags||[]).join(','):p[f]??'');slugTouched=true;$('formTitle').textContent='Beitrag bearbeiten';$('delete').hidden=false;renderList();preview()}
function fresh(){current=null;slugTouched=false;$('editor').reset();$('id').value='';$('date').value=today();$('author').value='Lokrogamer';$('formTitle').textContent='Neuer Beitrag';$('delete').hidden=true;renderList();preview()}
function download(){const blob=new Blob([JSON.stringify(byNewest(posts),null,2)+'\n'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='blogs.json';a.click();URL.revokeObjectURL(a.href);toast('blogs.json wurde exportiert.')}
try{posts=await getBlogs();fresh()}catch(e){toast(e.message);fresh()}
$('title').addEventListener('input',()=>{if(!slugTouched)$('slug').value=slugify($('title').value);preview()});$('slug').addEventListener('input',()=>{slugTouched=true;preview()});fields.filter(x=>!['title','slug'].includes(x)).forEach(id=>$(id).addEventListener('input',preview));$('editor').addEventListener('submit',e=>{e.preventDefault();const p=dataFromForm();if(posts.some(x=>x.slug===p.slug&&x.id!==current)){toast('Diese URL wird bereits verwendet.');return}posts=current?posts.map(x=>x.id===current?p:x):[...posts,p];current=p.id;saveLocal(posts);$('formTitle').textContent='Beitrag bearbeiten';$('delete').hidden=false;renderList();toast('Lokal gespeichert.');preview()});$('newPost').onclick=fresh;$('delete').onclick=()=>{if(!current||!confirm('Diesen Beitrag wirklich löschen?'))return;posts=posts.filter(x=>x.id!==current);saveLocal(posts);fresh();toast('Beitrag gelöscht.')};$('download').onclick=download;$('reset').onclick=()=>{if(confirm('Lokale Änderungen verwerfen und wieder blogs.json laden?')){clearLocal();location.reload()}};$('import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const json=JSON.parse(await file.text());if(!Array.isArray(json))throw Error();posts=json;saveLocal(posts);fresh();toast('Beiträge importiert.')}catch{toast('Die Datei ist keine gültige Blog-JSON-Datei.')}e.target.value=''});document.querySelectorAll('[data-wrap],[data-prefix]').forEach(button=>button.onclick=()=>{const input=$('content'),start=input.selectionStart,end=input.selectionEnd,text=input.value.slice(start,end)||'Text';let insert;if(button.dataset.wrap){const [before,after]=button.dataset.wrap.split('|');insert=before+text+after}else insert=button.dataset.prefix+text;input.setRangeText(insert,start,end,'end');input.focus();preview()});
